name: bouncing_ball
description: "A simple physics engine for ball movement with gravity, friction, and elasticity."
version: 0.0.1
homepage: https://github.com/MayarAboumahmood/bouncing_ball

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
